<!DOCTYPE html>
<html lang="en"><head>
  <title>Errors and Exceptions In Python</title>

  <meta name="description" content="Just Some Random Engineering, DIY Stuff" />

  
  <meta property="og:url" content="https://prinzpiuz.in/" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="prinzpiuz" />
  <meta
    property="og:description"
    content="Just Some Random Engineering, DIY Stuff"
  />
  <meta property="og:image" content="https://prinzpiuz.in/images/avatar.jpeg" />

  
  <meta name="twitter:card" content="summary_large_image" />
  <meta property="twitter:domain" content="prinzpiuz.in" />
  <meta property="twitter:url" content="https://prinzpiuz.in/" />
  <meta name="twitter:title" content="prinzpiuz" />
  <meta
    name="twitter:description"
    content="Just Some Random Engineering, DIY Stuff"
  />
  <meta
    name="twitter:image"
    content="https://prinzpiuz.in/images/avatar.jpeg"
  />

  

  <meta charset="utf-8" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
  <link rel="stylesheet" href="../../css/theme.css" />
  <script
    data-goatcounter="https://prinzpiuz.goatcounter.com/count"
    async
    src="//gc.zgo.at/count.js"
  ></script>
  
</head>
<body>
    <div id="content" class="mx-auto"><header class="container mt-sm-5 mt-4 mb-4 mt-xs-1">
    <div class="row">
        <div class="col-sm-4 col-12 text-sm-right text-center pt-sm-4">
            <a href="../../" class="text-decoration-none">
                <img id="home-image" class="rounded-circle"
                    
                        
                            src="../../images/avatar.jpeg"
                        
                    
                />
            </a>
        </div>
        <div class="col-sm-8 col-12 text-sm-left text-center">
            <h2 class="m-0 mb-2 mt-4">
                <a href="../../" class="text-decoration-none">
                    
                        PrinzPiuz
                    
                </a>
            </h2>
            <p class="text-muted mb-1">
                
                    Software Engineer | Ziff Davis | Cochin
                
            </p>
            <ul id="nav-links" class="list-inline mb-2">
                
                
                    <li class="list-inline-item">
                        <a class="badge badge-white " href="../../about/" title="About">About</a>
                    </li>
                
                    <li class="list-inline-item">
                        <a class="badge badge-white " href="../../post/" title="Posts">Posts</a>
                    </li>
                
                    <li class="list-inline-item">
                        <a class="badge badge-white " href="../../categories/" title="Categories">Categories</a>
                    </li>
                
                    <li class="list-inline-item">
                        <a class="badge badge-white " href="../../projects/my-projects/index.html" title="Projects">Projects</a>
                    </li>
                
            </ul>
            <ul id="nav-social" class="list-inline">
                
                    <li class="list-inline-item mr-3">
                        <a href="https://github.com/prinzpiuz" target="_blank">
                            <i class="fab fa-github fa-1x text-muted"></i>
                        </a>
                    </li>
                
                    <li class="list-inline-item mr-3">
                        <a href="https://twitter.com/prinzpiuz/" target="_blank">
                            <i class="fab fa-twitter fa-1x text-muted"></i>
                        </a>
                    </li>
                
                    <li class="list-inline-item mr-3">
                        <a href="https://elk.zone/aana.site/@prinzpiuz" target="_blank">
                            <i class="fab fa-mastodon text-muted"></i>
                        </a>
                    </li>
                
                    <li class="list-inline-item mr-3">
                        <a href="https://portfolio.pixelfed.social/prinzpiuz" target="_blank">
                            <i class="fas fa-images text-muted"></i>
                        </a>
                    </li>
                
            </ul>
        </div>
    </div>
    <hr />
</header>
<div class="container">
    <div class="pl-sm-2">
        <div class="mb-3">
            <h3 class="mb-0">Errors and Exceptions In Python</h3>
            
            <small class="text-muted">Published October 3, 2020</small>
            <small>üïê 7 Mins</small>

        </div>

        <article>
            <p>This blog is about How to manage Exceptions in python, this is more like notes I took while reading <a href="https://dusty.phillips.codes/">Dusty Phillips</a>&rsquo;s <a href="https://www.packtpub.com/product/python-3-object-oriented-programming-third-edition/9781789615852">Python 3 Object-oriented Programming</a>,
This post can be divided into</p>
<ul>
<li>why raise an exception?</li>
<li>what is happening when an exception is raised?</li>
<li>Handling exceptions</li>
<li>The exception hierarchy</li>
<li>Defining our exceptions</li>
</ul>
<h4 id="why-raise-an-exception">Why raise an exception?</h4>
<p>All the programs out there don&rsquo;t always output a valid result, errors can happen like it&rsquo;s not possible to
divide by zero, or to access the eighth item in a five-item list.
Want to see some errors? The easiest way to cause an exception is this.</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-shell" data-lang="shell">&gt;&gt;&gt; print <span style="color:#e6db74">&#34;hello world&#34;</span>
File <span style="color:#e6db74">&#34;&lt;stdin&gt;&#34;</span>, line <span style="color:#ae81ff">1</span>
print <span style="color:#e6db74">&#34;hello world&#34;</span>
^
SyntaxError: invalid syntax
</code></pre></div><p>This is a print statement in python 2, when we try to run this in the python 3 interpreter, we get this syntax error.
So exceptions are indicators of something wrong in our program, You may have noticed all the preceding built-in exceptions end with the name Error. In Python, the words error and exception are used almost interchangeably.
Errors are sometimes considered direr than exceptions, but they are dealt with in the same way. Indeed, all the error classes in the preceding example have
Exception (which extends BaseException ) as their superclass</p>
<h4 id="whats-happening-while-an-exception-is-raised">What&rsquo;s happening while an exception is raised?</h4>
<p>When an exception is raised, the program execution is stopped, and everything supposed to run after the exception will not run, if the exception is not managed correctly the program will exit with the error message
Take a look at this simple function:</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#66d9ef">def</span> <span style="color:#a6e22e">no_return</span>():
    print(<span style="color:#e6db74">&#34;I am about to raise an exception&#34;</span>)
    <span style="color:#66d9ef">raise</span> <span style="color:#a6e22e">Exception</span>(<span style="color:#e6db74">&#34;This is always raised&#34;</span>)
    print(<span style="color:#e6db74">&#34;This line will never execute&#34;</span>)
    <span style="color:#66d9ef">return</span> <span style="color:#e6db74">&#34;I won&#39;t be returned&#34;</span>
</code></pre></div><p>If we execute this function, we see that the first print call is executed and then the
exception is raised. The second print statement is never executed, and the return
statement never executes either</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#f92672">&gt;&gt;&gt;</span> no_return()
I am about to <span style="color:#66d9ef">raise</span> an exception
Traceback (most recent call last):
File <span style="color:#e6db74">&#34;&lt;stdin&gt;&#34;</span>, line <span style="color:#ae81ff">1</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
File <span style="color:#e6db74">&#34;exception_quits.py&#34;</span>, line <span style="color:#ae81ff">3</span>, <span style="color:#f92672">in</span> no_return
<span style="color:#66d9ef">raise</span> <span style="color:#a6e22e">Exception</span>(<span style="color:#e6db74">&#34;This is always raised&#34;</span>)
<span style="color:#a6e22e">Exception</span>: This <span style="color:#f92672">is</span> always raised
</code></pre></div><h4 id="handling-exceptions">Handling exceptions</h4>
<p>Even though if the program raises some exception, we can recover from it, by wrapping the code in a try &hellip; except clause, any code block that might throw an exception can be put inside the try block and thing that we want to do while an exception raise can be put inside the except block</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#66d9ef">try</span>:
    no_return()
<span style="color:#66d9ef">except</span>:
    print(<span style="color:#e6db74">&#34;I caught an exception&#34;</span>)
    print(<span style="color:#e6db74">&#34;executed after the exception&#34;</span>)
<span style="color:#75715e">#output</span>
I am about to <span style="color:#66d9ef">raise</span> an exception
I caught an exception
executed after the exception
</code></pre></div><p>The problem with the preceding code is that it will catch any type of exception.
What if we were writing some code that could raise both a TypeError and a ZeroDivisionError? We might want to catch the ZeroDivisionError, but let the TypeError propagate to the console</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#66d9ef">def</span> <span style="color:#a6e22e">funny_division</span>(divider):
    <span style="color:#66d9ef">try</span>:
        <span style="color:#66d9ef">return</span> <span style="color:#ae81ff">100</span> <span style="color:#f92672">/</span> divider
    <span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ZeroDivisionError</span>:
        <span style="color:#66d9ef">return</span> <span style="color:#e6db74">&#34;Zero is not a good idea!&#34;</span>
print(funny_division(<span style="color:#ae81ff">0</span>))
print(funny_division(<span style="color:#ae81ff">50.0</span>))
print(funny_division(<span style="color:#e6db74">&#34;hello&#34;</span>))
<span style="color:#75715e">#output</span>
Zero <span style="color:#f92672">is</span> <span style="color:#f92672">not</span> a good idea<span style="color:#960050;background-color:#1e0010">!</span>
<span style="color:#ae81ff">2.0</span>
Traceback (most recent call last):
File <span style="color:#e6db74">&#34;catch_specific_exception.py&#34;</span>, line <span style="color:#ae81ff">9</span>, <span style="color:#f92672">in</span> <span style="color:#f92672">&lt;</span>module<span style="color:#f92672">&gt;</span>
print(funny_division(<span style="color:#e6db74">&#34;hello&#34;</span>))
File <span style="color:#e6db74">&#34;catch_specific_exception.py&#34;</span>, line <span style="color:#ae81ff">3</span>, <span style="color:#f92672">in</span> funny_division
<span style="color:#66d9ef">return</span> <span style="color:#ae81ff">100</span> <span style="color:#f92672">/</span> anumber
<span style="color:#a6e22e">TypeError</span>: unsupported operand type(s) <span style="color:#66d9ef">for</span> <span style="color:#f92672">/</span>: <span style="color:#e6db74">&#39;int&#39;</span> <span style="color:#f92672">and</span> <span style="color:#e6db74">&#39;str&#39;</span><span style="color:#f92672">.</span>
</code></pre></div><p>So in the above code, we are avoiding all ZeroDivisionError but catching and printing all TypeError</p>
<h5 id="keywords-finally-and-else">keywords, finally, and else</h5>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#f92672">import</span> random
some_exceptions <span style="color:#f92672">=</span> [<span style="color:#a6e22e">ValueError</span>, <span style="color:#a6e22e">TypeError</span>, <span style="color:#a6e22e">IndexError</span>, <span style="color:#66d9ef">None</span>]
<span style="color:#66d9ef">try</span>:
    choice <span style="color:#f92672">=</span> random<span style="color:#f92672">.</span>choice(some_exceptions)
    print(<span style="color:#e6db74">&#34;raising </span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(choice))
<span style="color:#66d9ef">if</span> choice:
    <span style="color:#66d9ef">raise</span> choice(<span style="color:#e6db74">&#34;An error&#34;</span>)
<span style="color:#66d9ef">except</span> <span style="color:#a6e22e">ValueError</span>:
    print(<span style="color:#e6db74">&#34;Caught a ValueError&#34;</span>)
<span style="color:#66d9ef">except</span> <span style="color:#a6e22e">TypeError</span>:
    print(<span style="color:#e6db74">&#34;Caught a TypeError&#34;</span>)
<span style="color:#66d9ef">except</span> <span style="color:#a6e22e">Exception</span> <span style="color:#66d9ef">as</span> e:
    print(<span style="color:#e6db74">&#34;Caught some other error: </span><span style="color:#e6db74">%s</span><span style="color:#e6db74">&#34;</span> <span style="color:#f92672">%</span>
    ( e<span style="color:#f92672">.</span>__class__<span style="color:#f92672">.</span>__name__))
<span style="color:#66d9ef">else</span>:
    print(<span style="color:#e6db74">&#34;This code called if there is no exception&#34;</span>)
<span style="color:#66d9ef">finally</span>:
    print(<span style="color:#e6db74">&#34;This cleanup code is always called&#34;</span>)
</code></pre></div><p>If we run this example‚Äîwhich illustrates almost every conceivable exception
handling scenario‚Äîa few times, we&rsquo;ll get different output each time, depending
on which exception random chooses. Here are some example runs:</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-shell" data-lang="shell">$ python finally_and_else.py
raising None
This code called <span style="color:#66d9ef">if</span> there is no exception
This cleanup code is always called
$ python finally_and_else.py
raising &lt;class <span style="color:#e6db74">&#39;TypeError&#39;</span>&gt;
Caught a TypeError
This cleanup code is always called
$ python finally_and_else.py
raising &lt;class <span style="color:#e6db74">&#39;IndexError&#39;</span>&gt;
Caught some other error: IndexError
This cleanup code is always called
$ python finally_and_else.py
raising &lt;class <span style="color:#e6db74">&#39;ValueError&#39;</span>&gt;
Caught a ValueError
This cleanup code is always called
</code></pre></div><p>Note how the print statement in the <code>finally</code> clause is executed no matter what
happens. This is extremely useful when we need to perform certain tasks after
our code has finished running (even if an exception has occurred). Some common
examples include:</p>
<ul>
<li>Cleaning up an open database connection</li>
<li>Closing an open file</li>
<li>Sending a closing handshake over the network</li>
</ul>
<p>The <code>finally</code> clause is also very important when we execute a return statement
from inside a try clause. The <code>finally</code> handle will still be executed before the
value is returned</p>
<h4 id="the-exception-hierarchy">The exception hierarchy</h4>
<p>Most exceptions are a subclass of the Exception class, but this is not fully true. The exception itself inherits from a class called BaseException. All exceptions must extend the BaseException class or one of its subclasses.
When we use the <code>except</code> clause without specifying any type of exception, it will
catch all subclasses of <code>BaseException</code> which is to say, it will catch all exceptions,
including the two special ones. Since we almost always want these to get special
treatment, it is unwise to use the <code>except</code> statement without arguments. If you want
to catch all exceptions other than SystemExit and KeyboardInterrupt, explicitly catch Exception.
Furthermore, if you do want to catch all exceptions, I suggest using the syntax
except BaseException: instead of a raw <code>except</code>. This helps explicitly tell future
readers of your code that you are intentionally handling the special case exceptions.</p>
<h4 id="defining-our-own-exceptions">Defining our own exceptions</h4>
<p>All we have to do is inherit from the Exception class. We don&rsquo;t even have to add any
content to the class! We can, of course, extend BaseException directly, but then it
will not be caught by generic except Exception clauses.
Here&rsquo;s a simple exception we might use in a banking application:</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">InvalidWithdrawal</span>(<span style="color:#a6e22e">Exception</span>):
    <span style="color:#66d9ef">pass</span>
<span style="color:#66d9ef">raise</span> InvalidWithdrawal(<span style="color:#e6db74">&#34;You don&#39;t have $50 in your account&#34;</span>)
</code></pre></div><p>The last line shows how to call that exception
The Exception. __init** method is designed to accept any arguments and store them
as a tuple in an attribute named args . This makes exceptions easier to define without
needing to override init**.
So a more custom version of the above exception is like</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">InvalidWithdrawal</span>(<span style="color:#a6e22e">Exception</span>):
    <span style="color:#66d9ef">def</span> __init__(self, balance, amount):
        super()<span style="color:#f92672">.</span>__init__(<span style="color:#e6db74">&#34;account doesn&#39;t have $</span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(amount))
        self<span style="color:#f92672">.</span>amount <span style="color:#f92672">=</span> amount
        self<span style="color:#f92672">.</span>balance <span style="color:#f92672">=</span> balance
    <span style="color:#66d9ef">def</span> <span style="color:#a6e22e">overage</span>(self):
        <span style="color:#66d9ef">return</span> self<span style="color:#f92672">.</span>amount <span style="color:#f92672">-</span> self<span style="color:#f92672">.</span>balance
</code></pre></div><p>Here&rsquo;s how we would handle an InvalidWithdrawal exception if one was raised:</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-python" data-lang="python"><span style="color:#66d9ef">try</span>:
    <span style="color:#66d9ef">raise</span> InvalidWithdrawal(<span style="color:#ae81ff">25</span>, <span style="color:#ae81ff">50</span>)
<span style="color:#66d9ef">except</span> InvalidWithdrawal <span style="color:#66d9ef">as</span> e:
    print(<span style="color:#e6db74">&#34;I&#39;m sorry, but your withdrawal is &#34;</span>
    <span style="color:#e6db74">&#34;more than your balance by &#34;</span>
    <span style="color:#e6db74">&#34;$</span><span style="color:#e6db74">{}</span><span style="color:#e6db74">&#34;</span><span style="color:#f92672">.</span>format(e<span style="color:#f92672">.</span>overage()))
</code></pre></div><h4 id="conclusion">Conclusion</h4>
<p>while researching for this, I doubted like there is if..else then why try&hellip;except, and I got this to <a href="https://docs.python.org/3/glossary.html#term-eafp">read</a>. Python programmers tend to follow a model of Ask forgiveness rather than permission,
which is to say, they execute code and then deal with anything that goes wrong. The
alternative, to look before you leap, is generally frowned upon. There are a few reasons
for this, but the main one is that it shouldn&rsquo;t be necessary to burn CPU cycles looking
for an unusual situation that is not going to arise in the normal path through the
code. Therefore, it is wise to use exceptions for exceptional circumstances, even if
those circumstances are only a little bit exceptional. Taking this argument further,
we can see that the exception syntax is also effective for flow control. Like an, if statement, exceptions can be used for decision making, branching, and
message passing</p>
<h6 id="further-reads"><strong>Further reads</strong></h6>
<p><a href="https://docs.python.org/3/library/exceptions.html#bltin-exceptions">Built-in Exceptions in python</a>
<a href="https://docs.python.org/3/tutorial/errors.html#tut-userexceptions">User-defined Exceptions</a></p>

        </article>
    </div>
</div>
    </div>
    <footer class="text-center pb-1">
  <small class="text-muted">
     &copy; Copyright 2023, prinzpiuz<br />
    Built with üíö in <a href="https://gohugo.io/">Hugo</a>
    
  </small>
</footer>
</body>
</html>
